project:
  type: book
  output-dir: _book

execute:
  freeze: auto

book:
  title: "Applied Geodata Science"
  subtitle: ""
  author: "Benjamin Stocker, Koen Hufkens, Pepa Ar√°n, and Pascal Schneider"
  date: "2023/11/07"
  page-navigation: true
  chapters:
    # - index.qmd
    # - intro.qmd
    # - getting_started.qmd
    # - programming_primers.qmd
    # - data_wrangling.qmd
    # - data_vis.qmd
    # - data_variety.qmd
    # - open_science.qmd
    # - code_management.qmd
    # - regression_classification.qmd
    # - supervised_ml_I.qmd
    # - supervised_ml_II.qmd
    # - randomforest.qmd
    # - interpretable-ml.qmd
    - appendix.qmd
    # - references.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/stineb/agds_book/
  sharing: [twitter, facebook]
  navbar:
    title: " "
    logo: "images/logo.png"
    background: "#3A3A3A"
    search: true
    right:
      - text: "Home"
        file: index.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
